fail_fast: true
repos:
    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v3.1.0
        hooks:
            -   id: reorder-python-imports
    -   repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
            - id: black
              language_version: python3.9
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.1.0
        hooks:
            -   id: check-merge-conflict
            -   id: detect-private-key
            -   id: check-symlinks
            -   id: check-toml
            -   id: check-xml
            -   id: check-yaml
            -   id: forbid-new-submodules
            -   id: mixed-line-ending
            -   id: trailing-whitespace
                language: python
    -   repo: https://github.com/pre-commit/pygrep-hooks
        rev: v1.9.0 # Use the ref you want to point at
        hooks:
            -   id: python-no-eval
            -   id: python-no-log-warn
            -   id: python-use-type-annotations
    -   repo: https://github.com/asottile/pyupgrade
        rev: v2.31.1
        hooks:
            -   id: pyupgrade
                args: [ --py311-plus ]
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.9.2
        hooks:
            -   id: flake8
    -   repo: https://github.com/pre-commit/mirrors-scss-lint
        rev: v0.59.0
        hooks:
            -   id: scss-lint
